Callback to promise
AnnaVerba/FastifyApp pull request #2
Opened 2022-10-25 07:25 UTC by AnnaVerba

2022-10-25 08:20 UTC, MaxLogvyniukFive requested changes

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on consumer/app.js
> +  const amqpServer = 'amqp://localhost:5672';
Move to .env

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on consumer/app.js
> +connect();
Connect need to use after initialization

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on consumer/app.js
> +    console.log(error);
Add logger

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on consumer/app.js
> +    durable: true,
Use variable for true

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on consumer/package-lock.json
> +{
Use yarn instead of npm

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on src/main.ts
> +  await app.listen(8002);
Move to .env

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on src/movie/MessagingService.ts
> +    routingKey: 'replay.#',
Move in variable 'replay.#', Create shared folder and file consts.ts

2022-10-25 08:20 UTC, MaxLogvyniukFive commented on src/movie/MessagingService.ts
> +    console.log(
Logger

2022-10-25 11:05 UTC, MaxLogvyniukFive requested changes
Remove dist folder and add it to git ignore

2022-10-25 11:05 UTC, MaxLogvyniukFive commented on consumer/app.ts
> +const trueOrFalse = true;
Name of variable must tell what it contains

2022-10-25 11:05 UTC, MaxLogvyniukFive commented on consumer/dist/consumer/app.js
> +'use strict';
We not pushing dist to git

2022-10-25 11:05 UTC, MaxLogvyniukFive commented on consumer/logs/info.log
> +info: Oct-25-2022 13:44:03: 	 [x] Received %s
Add logs to gitignore

2022-10-26 11:32 UTC, MaxLogvyniukFive commented on consumer/package-lock.json
> +{
Please rermove package-lock and use yarn to install node modules

2022-10-26 11:36 UTC, MaxLogvyniukFive requested changes

2022-10-26 11:36 UTC, MaxLogvyniukFive commented on consumer/app.ts
> +const amqpServer = 'amqp://localhost:5672';
Move to .env this url

2022-10-26 11:36 UTC, MaxLogvyniukFive commented on consumer/app.ts
> +const durableIsTrue = true;
Rename to "isDurable"

2022-10-26 11:36 UTC, MaxLogvyniukFive commented on src/main.ts
> +  // app.use(winston);
Why commented?

2022-10-26 11:36 UTC, MaxLogvyniukFive commented on src/modeles/messaging_with_rabbitqm/MessagingService.ts
> +  exchange: 'exchange1',
Also move to consts

2022-10-26 11:36 UTC, MaxLogvyniukFive commented on src/modeles/messaging_with_rabbitqm/MessagingService.ts
> +  queue: 'hello',
Sme here

2022-10-26 11:36 UTC, MaxLogvyniukFive commented on src/modeles/movie/movie.service.ts
> +    const totalMessages = 20;
Move to .env

2022-10-26 11:36 UTC, MaxLogvyniukFive commented on src/modeles/movie/movie.service.ts
> +        'hardTestExchange',
move to consts

2022-11-11 20:59 UTC, MartinBrown-khpi requested changes

2022-11-11 20:59 UTC, MartinBrown-khpi commented on .env
>  database='postgres'
do not store passwords/keys/secrets in the repo

2022-11-11 20:59 UTC, MartinBrown-khpi commented on consumer/.gitignore
> +dist
.gitignore works in all subdirectories by default, isn't it?
In any case, you can divide the project into submodules
https://github.blog/2016-02-01-working-with-submodules/

2022-11-11 20:59 UTC, MartinBrown-khpi commented on consumer/app.ts
> +let consumedMessages = 0;
looks like config

2022-11-20 19:25 UTC, closed without merging